documents = [
{"id": 0, "content": "Battery drains very quickly after full charge.", "metadata": {"source": "review1"}},
{"id": 1, "content": "Amazing camera quality with sharp and vibrant photos.", "metadata": {"source": "review2"}},
{"id": 2, "content": "Charging takes too long and the phone heats up.", "metadata": {"source": "review3"}},
{"id": 3, "content": "Excellent display but battery life is disappointing.", "metadata": {"source": "review4"}},
{"id": 4, "content": "Sound quality is clear and loud for music playback.", "metadata": {"source": "review5"}},
{"id": 5, "content": "Battery lasts all day even with heavy usage.", "metadata": {"source": "review6"}},
{"id": 6, "content": "Camera struggles in low light conditions.", "metadata": {"source": "review7"}},
{"id": 7, "content": "The device overheats while gaming.", "metadata": {"source": "review8"}},
{"id": 8, "content": "Fast charging works perfectly and saves time.", "metadata": {"source": "review9"}},
{"id": 9, "content": "Screen brightness is excellent outdoors.", "metadata": {"source": "review10"}},
{"id": 10, "content": "Battery backup is poor and needs frequent charging.", "metadata": {"source": "review11"}},
{"id": 11, "content": "Camera stabilization works really well for videos.", "metadata": {"source": "review12"}},
{"id": 12, "content": "Performance is smooth and apps open instantly.", "metadata": {"source": "review13"}},
{"id": 13, "content": "The phone becomes warm during long video calls.", "metadata": {"source": "review14"}},
{"id": 14, "content": "Battery drains overnight even when idle.", "metadata": {"source": "review15"}},
{"id": 15, "content": "Audio output is weak compared to other models.", "metadata": {"source": "review16"}},
{"id": 16, "content": "The display colors look very natural and vivid.", "metadata": {"source": "review17"}},
{"id": 17, "content": "Charging cable included is low quality.", "metadata": {"source": "review18"}},
{"id": 18, "content": "Battery performance improved after software update.", "metadata": {"source": "review19"}},
{"id": 19, "content": "Camera captures detailed portraits beautifully.", "metadata": {"source": "review20"}},
{"id": 20, "content": "The phone freezes occasionally during multitasking.", "metadata": {"source": "review21"}},
{"id": 21, "content": "Battery percentage drops suddenly from 20 to 5.", "metadata": {"source": "review22"}},
{"id": 22, "content": "The speaker produces immersive stereo sound.", "metadata": {"source": "review23"}},
{"id": 23, "content": "Charging speed is slower than advertised.", "metadata": {"source": "review24"}},
{"id": 24, "content": "Battery lasts longer than my previous phone.", "metadata": {"source": "review25"}},
{"id": 25, "content": "Camera zoom quality is impressive.", "metadata": {"source": "review26"}},
{"id": 26, "content": "Device heats up while charging.", "metadata": {"source": "review27"}},
{"id": 27, "content": "The display refresh rate makes scrolling smooth.", "metadata": {"source": "review28"}},
{"id": 28, "content": "Battery life is terrible for gaming.", "metadata": {"source": "review29"}},
{"id": 29, "content": "Photos come out blurry sometimes.", "metadata": {"source": "review30"}},
{"id": 30, "content": "Battery drains quickly when using mobile data.", "metadata": {"source": "review31"}},
{"id": 31, "content": "Charging port feels loose and unreliable.", "metadata": {"source": "review32"}},
{"id": 32, "content": "Battery backup is decent for normal use.", "metadata": {"source": "review33"}},
{"id": 33, "content": "Camera color accuracy is outstanding.", "metadata": {"source": "review34"}},
{"id": 34, "content": "Phone gets hot after extended gaming sessions.", "metadata": {"source": "review35"}},
{"id": 35, "content": "Battery charges from 0 to 50 percent very fast.", "metadata": {"source": "review36"}},
{"id": 36, "content": "Sound clarity during calls is excellent.", "metadata": {"source": "review37"}},
{"id": 37, "content": "Battery drains faster after recent update.", "metadata": {"source": "review38"}},
{"id": 38, "content": "Camera autofocus is slow.", "metadata": {"source": "review39"}},
{"id": 39, "content": "Display resolution makes videos look sharp.", "metadata": {"source": "review40"}},
{"id": 40, "content": "Battery barely lasts half a day.", "metadata": {"source": "review41"}},
{"id": 41, "content": "Charging adapter heats up during use.", "metadata": {"source": "review42"}},
{"id": 42, "content": "Camera night mode produces bright images.", "metadata": {"source": "review43"}},
{"id": 43, "content": "Battery health degraded within few months.", "metadata": {"source": "review44"}},
{"id": 44, "content": "Performance is excellent for gaming.", "metadata": {"source": "review45"}},
{"id": 45, "content": "Battery lasts more than 24 hours.", "metadata": {"source": "review46"}},
{"id": 46, "content": "Camera lens scratches easily.", "metadata": {"source": "review47"}},
{"id": 47, "content": "Battery charging is inconsistent.", "metadata": {"source": "review48"}},
{"id": 48, "content": "Display touch response is very accurate.", "metadata": {"source": "review49"}},
{"id": 49, "content": "Battery drains quickly while streaming videos.", "metadata": {"source": "review50"}},
{"id": 50, "content": "Camera HDR feature works great.", "metadata": {"source": "review51"}},
{"id": 51, "content": "Battery lasts long with power saving mode.", "metadata": {"source": "review52"}},
{"id": 52, "content": "The device overheats in sunlight.", "metadata": {"source": "review53"}},
{"id": 53, "content": "Battery life is satisfactory for daily tasks.", "metadata": {"source": "review54"}},
{"id": 54, "content": "Camera front selfie quality is amazing.", "metadata": {"source": "review55"}},
{"id": 55, "content": "Battery drains quickly during video recording.", "metadata": {"source": "review56"}},
{"id": 56, "content": "Charging indicator sometimes fails to show.", "metadata": {"source": "review57"}},
{"id": 57, "content": "Battery life improved after calibration.", "metadata": {"source": "review58"}},
{"id": 58, "content": "Camera performance is average in daylight.", "metadata": {"source": "review59"}},
{"id": 59, "content": "Battery percentage fluctuates randomly.", "metadata": {"source": "review60"}},
{"id": 60, "content": "Sound output is rich and balanced.", "metadata": {"source": "review61"}},
{"id": 61, "content": "Battery overheats while charging.", "metadata": {"source": "review62"}},
{"id": 62, "content": "Camera video recording is smooth and stable.", "metadata": {"source": "review63"}},
{"id": 63, "content": "Battery life is poor after heavy gaming.", "metadata": {"source": "review64"}},
{"id": 64, "content": "Charging speed is very impressive.", "metadata": {"source": "review65"}},
{"id": 65, "content": "Battery drains even when not in use.", "metadata": {"source": "review66"}},
{"id": 66, "content": "Camera exposure control is accurate.", "metadata": {"source": "review67"}},
{"id": 67, "content": "Battery capacity feels smaller than advertised.", "metadata": {"source": "review68"}},
{"id": 68, "content": "Display brightness automatically adjusts well.", "metadata": {"source": "review69"}},
{"id": 69, "content": "Battery lasts through an entire workday.", "metadata": {"source": "review70"}},
{"id": 70, "content": "Camera struggles with motion shots.", "metadata": {"source": "review71"}},
{"id": 71, "content": "Battery drains quickly while using GPS.", "metadata": {"source": "review72"}},
{"id": 72, "content": "Charging port stopped working after few months.", "metadata": {"source": "review73"}},
{"id": 73, "content": "Battery life is excellent for streaming music.", "metadata": {"source": "review74"}},
{"id": 74, "content": "Camera produces natural skin tones.", "metadata": {"source": "review75"}},
{"id": 75, "content": "Battery gets warm during fast charging.", "metadata": {"source": "review76"}},
{"id": 76, "content": "Performance is laggy with multiple apps open.", "metadata": {"source": "review77"}},
{"id": 77, "content": "Battery backup is impressive overall.", "metadata": {"source": "review78"}},
{"id": 78, "content": "Camera shutter speed is quick.", "metadata": {"source": "review79"}},
{"id": 79, "content": "Battery drains rapidly when Bluetooth is on.", "metadata": {"source": "review80"}},
{"id": 80, "content": "Charging speed meets expectations.", "metadata": {"source": "review81"}},
{"id": 81, "content": "Battery lasts longer in airplane mode.", "metadata": {"source": "review82"}},
{"id": 82, "content": "Camera detail level is fantastic.", "metadata": {"source": "review83"}},
{"id": 83, "content": "Battery drains quickly in cold weather.", "metadata": {"source": "review84"}},
{"id": 84, "content": "Display size is perfect for watching movies.", "metadata": {"source": "review85"}},
{"id": 85, "content": "Battery performance is unreliable.", "metadata": {"source": "review86"}},
{"id": 86, "content": "Camera portrait mode is stunning.", "metadata": {"source": "review87"}},
{"id": 87, "content": "Battery loses charge rapidly during calls.", "metadata": {"source": "review88"}},
{"id": 88, "content": "Charging works flawlessly every time.", "metadata": {"source": "review89"}},
{"id": 89, "content": "Battery life is consistent and stable.", "metadata": {"source": "review90"}},
{"id": 90, "content": "Camera sharpness is impressive even at zoom.", "metadata": {"source": "review91"}},
{"id": 91, "content": "Battery drains quickly with screen brightness high.", "metadata": {"source": "review92"}},
{"id": 92, "content": "Charging cable broke within weeks.", "metadata": {"source": "review93"}},
{"id": 93, "content": "Battery lasts surprisingly long on standby.", "metadata": {"source": "review94"}},
{"id": 94, "content": "Camera captures vibrant sunset photos.", "metadata": {"source": "review95"}},
{"id": 95, "content": "Battery drains extremely fast after update.", "metadata": {"source": "review96"}},
{"id": 96, "content": "Sound output is clear even at max volume.", "metadata": {"source": "review97"}},
{"id": 97, "content": "Battery life is not as advertised.", "metadata": {"source": "review98"}},
{"id": 98, "content": "Camera quality is decent for the price.", "metadata": {"source": "review99"}},
{"id": 99, "content": "Battery drains quickly while playing games.", "metadata": {"source": "review100"}},
{"id": 100, "content": "Charging is reliable and efficient.", "metadata": {"source": "review101"}},
{"id": 101, "content": "Battery holds charge well over time.", "metadata": {"source": "review102"}},
{"id": 102, "content": "Camera struggles in indoor lighting.", "metadata": {"source": "review103"}},
{"id": 103, "content": "Battery overheats during long calls.", "metadata": {"source": "review104"}},
{"id": 104, "content": "Display clarity is stunning.", "metadata": {"source": "review105"}},
{"id": 105, "content": "Battery drains quickly when hotspot is enabled.", "metadata": {"source": "review106"}},
{"id": 106, "content": "Camera video stabilization is excellent.", "metadata": {"source": "review107"}},
{"id": 107, "content": "Battery life is average but manageable.", "metadata": {"source": "review108"}},
{"id": 108, "content": "Charging speed exceeded my expectations.", "metadata": {"source": "review109"}},
{"id": 109, "content": "Battery drains unexpectedly at low percentage.", "metadata": {"source": "review110"}},
{"id": 110, "content": "Camera delivers crisp and clear images.", "metadata": {"source": "review111"}},
{"id": 111, "content": "Battery performance is solid after updates.", "metadata": {"source": "review112"}},
{"id": 112, "content": "Device heats up while fast charging.", "metadata": {"source": "review113"}},
{"id": 113, "content": "Battery drains quickly with 5G enabled.", "metadata": {"source": "review114"}},
{"id": 114, "content": "Camera dynamic range is impressive.", "metadata": {"source": "review115"}},
{"id": 115, "content": "Battery backup is excellent overall.", "metadata": {"source": "review116"}},
{"id": 116, "content": "Charging speed is inconsistent sometimes.", "metadata": {"source": "review117"}},
{"id": 117, "content": "Battery drains too fast during navigation.", "metadata": {"source": "review118"}},
{"id": 118, "content": "Camera performance is top notch.", "metadata": {"source": "review119"}},
{"id": 119, "content": "Battery lasts longer than expected.", "metadata": {"source": "review120"}}
]
